version: '3'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    container_name: elasticsearch1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch1.yml:/usr/share/elasticsearch/config/elasticsearch.yml  
      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties 
    networks:
      - esnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: elasticsearch2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9201
    volumes:
      - ./elasticsearch2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties   
    networks:
      - esnet

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: elasticsearch3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9202
    volumes:
      - ./elasticsearch3.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties   
    networks:
      - esnet

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.10.0
  #   container_name: kibana
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch1:9200
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - esnet
  #   volumes:
  #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml      
  #   depends_on:
  #     - elasticsearch1
  #     - elasticsearch2
  #     - elasticsearch3



networks:
  esnet:
