version: '3'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0-SNAPSHOT
    container_name: elasticsearch1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9201
    volumes:
      - ./elasticsearch1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore    
      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties 
    networks:
      - esnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0-SNAPSHOT
    container_name: elasticsearch2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore 
      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties   
    networks:
      - esnet
    depends_on:
      - elasticsearch1  

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0-SNAPSHOT
    container_name: elasticsearch3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9202
    volumes:
      - ./elasticsearch3.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore 
      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties   
    networks:
      - esnet
    depends_on:
      - elasticsearch1

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.2.0-SNAPSHOT
  #   container_name: kibana
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch1:9200
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - esnet
  #   volumes:
  #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml      
  #   depends_on:
  #     - elasticsearch1
  #     - elasticsearch2
  #     - elasticsearch3

  minio:
    image: minio/minio
    container_name: minio 
    command: server /data
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    ports:
      - 9000:9000
    volumes:
      - /data:/home/jakelandis/workspace/data/minio
    networks:
      - esnet

networks:
  esnet:
